<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>ArxisStudio.Extensibility</RootNamespace>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../ArxisStudio.Sdk/ArxisStudio.Sdk.csproj"/>
        <ProjectReference Include="../ArxisStudio.Shell/ArxisStudio.Shell.csproj"/>
    </ItemGroup>

</Project>
